# NOTA PARA TRUENAS SCALE:
# Este Compose descarga las imágenes compiladas directamente desde GitHub Container Registry (GHCR)
# Es ideal para ser importado en la interfaz de Custom Apps de TrueNAS o Dockge sin requerir código fuente.

services:
  scraper:
    # Imagen referenciada desde GitHub Container Registry
    image: ghcr.io/blu777/precios-tiago/miraprecios-scraper:latest
    container_name: miraprecios_scraper
    volumes:
      # Mantenemos el Dataset de DATOS porque el Scraper aún guarda JSONs temporales aquí
      - /mnt/HMS/Precios/data:/app/data
    environment:
      - PUID=568
      - PGID=568
      - TURSO_DATABASE_URL=libsql://preciostiago-tiagonatale.aws-us-east-2.turso.io
      - TURSO_AUTH_TOKEN=eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3ODAzNDgxNTgsImlkIjoiMDE5ZTgzNTQtMjIwMS03YmE1LTgzMWQtMTBhMmU1NGE1NmJjIiwicmlkIjoiYWJmMTNhNmMtNGYxNS00NjFkLThhNWMtNDg3MzdkNjNlYWIyIn0.l-LixF0bNMnpQhOOcl94oRSdQMYqwKmQxqdqn6z1AOGlsiJpUkRqxuCYr0sRhyAJae635sYXnc6PMoCOqfYfDg
    restart: unless-stopped
